#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cgit
Version  : 1.1
Release  : 1
URL      : https://git.zx2c4.com/cgit/snapshot/cgit-1.1.tar.xz
Source0  : https://git.zx2c4.com/cgit/snapshot/cgit-1.1.tar.xz
Source1  : https://www.kernel.org/pub/software/scm/git/git-2.10.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSL-1.0 GPL-2.0
Requires: cgit-bin
Requires: cgit-data
BuildRequires : go
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
Patch1: 0001-Makefile-set-standard-paths.patch

%description
cgit - CGI for Git
==================
This is an attempt to create a fast web interface for the Git SCM, using a
built-in cache to decrease server I/O pressure.

%package bin
Summary: bin components for the cgit package.
Group: Binaries
Requires: cgit-data

%description bin
bin components for the cgit package.


%package data
Summary: data components for the cgit package.
Group: Data

%description data
data components for the cgit package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n cgit-1.1
mkdir -p %{_topdir}/BUILD/cgit-1.1/git
mv %{_topdir}/BUILD/git-2.10.2/* %{_topdir}/BUILD/cgit-1.1/git
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516294599
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1516294599
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/libexec/cgit/filters/about-formatting.sh
/usr/libexec/cgit/filters/commit-links.sh
/usr/libexec/cgit/filters/email-gravatar.lua
/usr/libexec/cgit/filters/email-gravatar.py
/usr/libexec/cgit/filters/email-libravatar.lua
/usr/libexec/cgit/filters/gentoo-ldap-authentication.lua
/usr/libexec/cgit/filters/html-converters/man2html
/usr/libexec/cgit/filters/html-converters/md2html
/usr/libexec/cgit/filters/html-converters/rst2html
/usr/libexec/cgit/filters/html-converters/txt2html
/usr/libexec/cgit/filters/owner-example.lua
/usr/libexec/cgit/filters/simple-authentication.lua
/usr/libexec/cgit/filters/syntax-highlighting.py
/usr/libexec/cgit/filters/syntax-highlighting.sh

%files data
%defattr(-,root,root,-)
/usr/share/cgit/cgit.css
/usr/share/cgit/cgit.png
/usr/share/cgit/favicon.ico
/usr/share/cgit/robots.txt
/usr/share/httpd/www/cgi-bin/cgit
